### ISSUE TITLE
BSP settings not applied

### ISSUE THREAD

**Issue by SajedeNick1999** [SiliconLabs/Xilinx#1]
Hello.
I use ucOS-iii and uc-TCP/IP and this repository for xilinx.
I want to create 10 UDP sockets.
I change NET_SOCK_CFG_SOCK_NBR_UDP in BSP setting of project.
But still I can open just 7 socket and after that I receive  NET_SOCK_ERR_NONE_AVAIL as error
Is there any problem with xilinx BSP setting?
what I have to do?
How can I debug OS source files? I can't see them in repository

Thank you.

**Comment by forg0ne** [comment]
The source code is not included in the Xilinx repository.
You have to manually include the code you want to be able to rebuild.
All products are available from the Weston-Embedded github page.
