### ISSUE TITLE
Generate BSP failed

### ISSUE THREAD

**Issue by ynt1988** [SiliconLabs/Xilinx#3]
I follow the guide, new local repository with this SDK. And I can choose ucos when generate BSP in Xilinx SDK tool. However, error happens during generating. Errors say "Problem running tcl command ::sw_ucos_common_v1_45::generate: error copying .../micrium_source/uC-CPU/Cfg/Template/cpu_cfg.h to .... failed. Because this file is not existing."

PS： I download master or 1.50 branch, but imported local repository shows 1.45. Why? Any Problem?

**Comment by forg0ne** [comment]
The guide was written when the Xilinx repository was delivered with the RTOS source. When the software was open-sourced, the source code for each component was segmented into its own repository. You need to reassemble the Xilinx repository by copying the the source code for each component into the Xilinx Repository folder.

The 1.45 version was an oversight when the software was open-sourced. It shouldn't cause any issues.

**Comment by ynt1988** [comment]
Thank you. It works.
